# OPTIONAL: Add this Dockerfile to your challenge if it requires hosting (all web challenges require hosting)
# If your challenge does not require hosting, do not add this folder!

# If you don't know how to write a Dockerfile...
## 1. Refer to the examples and try to learn how to Dockerize (https://docs.docker.com/get-started/). (pls)
## 2. Create a ticket in the Gryphons Discord server and ask for help.
## 3. Indicate in the submission form that you need help with Dockerizing your challenge,
##    and add the files you currently have to the `service` folder manually.